// Chuyển đổi sang chữ Nhật
const inputBarLists = document.querySelectorAll(".inputBar");
const pronuciation = document.getElementById("pronuciation");
const pronuciationCopy = document.getElementById("pronuciationCopy");
var car;
var ship;
for (const inputBar of inputBarLists) {
    inputBar.onkeyup = function (e) {
        car = inputBar.value.toLowerCase();
        car = car.replace(/_/g, "ー");
        car = car.replace(/[ôō]/g, "oう");
        car = car.replace(/[ūû]/g, "uう");
        car = car.replace(/[âā]/g, "aあ");
        car = car.replace(/[îī]/g, "iい");
        car = car.replace(/[êē]/g, "eい");

        car = car.replace(/n/g, "ん");
        car = car.replace(/q/g, "っ");
        car = car.replace(/tsu/g, "つ");
        car = car.replace(/dzu/g, "づ");
        car = car.replace(/dju/g, "づ");
        car = car.replace(/dji/g, "ぢ");
        car = car.replace(/kya/g, "きゃ");
        car = car.replace(/kyu/g, "きゅ");
        car = car.replace(/kyo/g, "きょ");
        car = car.replace(/んya/g, "にゃ");
        car = car.replace(/んyu/g, "にゅ");
        car = car.replace(/んyo/g, "にょ");
        car = car.replace(/sha/g, "しゃ");
        car = car.replace(/shi/g, "し");
        car = car.replace(/shu/g, "しゅ");
        car = car.replace(/sho/g, "しょ");
        car = car.replace(/chi/g, "ち");
        car = car.replace(/cha/g, "ちゃ");
        car = car.replace(/chu/g, "ちゅ");
        car = car.replace(/cho/g, "ちょ");
        car = car.replace(/hya/g, "ひゃ");
        car = car.replace(/hyu/g, "ひゅ");
        car = car.replace(/hyo/g, "ひょ");
        car = car.replace(/mya/g, "みゃ");
        car = car.replace(/myu/g, "みゅ");
        car = car.replace(/myo/g, "みょ");
        car = car.replace(/rya/g, "りゃ");
        car = car.replace(/ryu/g, "りゅ");
        car = car.replace(/ryo/g, "りょ");
        car = car.replace(/gya/g, "ぎゃ");
        car = car.replace(/gyu/g, "ぎゅ");
        car = car.replace(/gyo/g, "ぎょ");
        car = car.replace(/bya/g, "びゃ");
        car = car.replace(/byu/g, "びゅ");
        car = car.replace(/byo/g, "びょ");
        car = car.replace(/pya/g, "ぴゃ");
        car = car.replace(/pyu/g, "ぴゅ");
        car = car.replace(/pyo/g, "ぴょ");
        car = car.replace(/ja/g, "じゃ");
        car = car.replace(/ju/g, "じゅ");
        car = car.replace(/jo/g, "じょ");
        car = car.replace(/ba/g, "ば");
        car = car.replace(/da/g, "だ");
        car = car.replace(/ga/g, "が");
        car = car.replace(/ha/g, "は");
        car = car.replace(/ka/g, "か");
        car = car.replace(/ma/g, "ま");
        car = car.replace(/んa/g, "な");
        car = car.replace(/pa/g, "ぱ");
        car = car.replace(/ra/g, "ら");
        car = car.replace(/sa/g, "さ");
        car = car.replace(/ta/g, "た");
        car = car.replace(/wa/g, "わ");
        car = car.replace(/ya/g, "や");
        car = car.replace(/za/g, "ざ");
        car = car.replace(/be/g, "べ");
        car = car.replace(/de/g, "で");
        car = car.replace(/ge/g, "げ");
        car = car.replace(/he/g, "へ");
        car = car.replace(/ke/g, "け");
        car = car.replace(/me/g, "め");
        car = car.replace(/んe/g, "ね");
        car = car.replace(/pe/g, "ぺ");
        car = car.replace(/re/g, "れ");
        car = car.replace(/we/g, "ゑ");
        car = car.replace(/se/g, "せ");
        car = car.replace(/te/g, "て");
        car = car.replace(/ze/g, "ぜ");
        car = car.replace(/bi/g, "び");
        car = car.replace(/gi/g, "ぎ");
        car = car.replace(/hi/g, "ひ");
        car = car.replace(/ki/g, "き");
        car = car.replace(/si/g, "し");
        car = car.replace(/ti/g, "ち");
        car = car.replace(/mi/g, "み");
        car = car.replace(/んi/g, "に");
        car = car.replace(/pi/g, "ぴ");
        car = car.replace(/ri/g, "り");
        car = car.replace(/wi/g, "ゐ");
        car = car.replace(/ji/g, "じ");
        car = car.replace(/zi/g, "じ");
        car = car.replace(/bo/g, "ぼ");
        car = car.replace(/do/g, "ど");
        car = car.replace(/go/g, "ご");
        car = car.replace(/ho/g, "ほ");
        car = car.replace(/ko/g, "こ");
        car = car.replace(/mo/g, "も");
        car = car.replace(/んo/g, "の");
        car = car.replace(/po/g, "ぽ");
        car = car.replace(/ro/g, "ろ");
        car = car.replace(/so/g, "そ");
        car = car.replace(/to/g, "と");
        car = car.replace(/wo/g, "を");
        car = car.replace(/yo/g, "よ");
        car = car.replace(/zo/g, "ぞ");
        car = car.replace(/bu/g, "ぶ");
        car = car.replace(/gu/g, "ぐ");
        car = car.replace(/fu/g, "ふ");
        car = car.replace(/hu/g, "ふ");
        car = car.replace(/ku/g, "く");
        car = car.replace(/mu/g, "む");
        car = car.replace(/んu/g, "ぬ");
        car = car.replace(/pu/g, "ぷ");
        car = car.replace(/ru/g, "る");
        car = car.replace(/su/g, "す");
        car = car.replace(/tu/g, "つ"); //
        car = car.replace(/yu/g, "ゆ");
        car = car.replace(/zu/g, "ず");

        // cas des doublons
        car = car.replace(/di/g, "ぢ");
        car = car.replace(/じ=/g, "ぢ");
        car = car.replace(/du/g, "づ");
        car = car.replace(/ず=/g, "づ");

        car = car.replace(/a/g, "あ");
        car = car.replace(/e/g, "え");
        car = car.replace(/i/g, "い");
        car = car.replace(/o/g, "お");
        car = car.replace(/u/g, "う");
        car = car.replace(/v/g, "ゔ");

        car = car.replace(/つ=/g, "っ");
        car = car.replace(/あ=/g, "ぁ");
        car = car.replace(/い=/g, "ぃ");
        car = car.replace(/う=/g, "ぅ");
        car = car.replace(/え=/g, "ぇ");
        car = car.replace(/お=/g, "ぉ");
        car = car.replace(/や=/g, "ゃ");
        car = car.replace(/ゆ=/g, "ゅ");
        car = car.replace(/よ=/g, "ょ");

        car = car.replace(/\./g, "。");
        car = car.replace(/\,/g, "、");
        car = car.replace(/\!/g, "！");
        car = car.replace(/\?/g, "？");
        car = car.replace(/\:/g, "：");
        car = car.replace(/\(/g, "（");
        car = car.replace(/\)/g, "）");
        car = car.replace(/\[/g, "［");
        car = car.replace(/\]/g, "］");
        car = car.replace(/\«/g, "「");
        car = car.replace(/\»/g, "」");

        const startPos = inputBar.selectionStart;
        const endPos = inputBar.selectionEnd;

        const beforeLen = inputBar.value.length;
        const afterLen = car.length;
        const adjustment = afterLen - beforeLen;

        inputBar.value = car;

        inputBar.selectionStart = startPos + adjustment;
        inputBar.selectionEnd = endPos + adjustment;

        var obj = inputBar;
        obj.focus();
        obj.scrollTop = obj.scrollHeight;

        ship = car;
        ship = ship.replace(/ー/g, "_ ");

        ship = ship.replace(/ん/g, "n ");
        ship = ship.replace(/っ/g, "q ");
        ship = ship.replace(/つ/g, "tsu ");
        ship = ship.replace(/づ/g, "dzu ");
        ship = ship.replace(/づ/g, "dju ");
        ship = ship.replace(/ぢ/g, "dji ");
        ship = ship.replace(/きゃ/g, "kya ");
        ship = ship.replace(/きゅ/g, "kyu ");
        ship = ship.replace(/きょ/g, "kyo ");
        ship = ship.replace(/にゃ/g, "nya ");
        ship = ship.replace(/にゅ/g, "nyu ");
        ship = ship.replace(/にょ/g, "nyo ");
        ship = ship.replace(/しゃ/g, "sha ");
        ship = ship.replace(/し/g, "shi ");
        ship = ship.replace(/しゅ/g, "shu ");
        ship = ship.replace(/しょ/g, "sho ");
        ship = ship.replace(/ちゃ/g, "cha ");
        ship = ship.replace(/ち/g, "chi ");
        ship = ship.replace(/ちゅ/g, "chu ");
        ship = ship.replace(/ちょ/g, "cho ");
        ship = ship.replace(/ひゃ/g, "hya ");
        ship = ship.replace(/ひゅ/g, "hyu ");
        ship = ship.replace(/ひょ/g, "hyo ");
        ship = ship.replace(/みゃ/g, "mya ");
        ship = ship.replace(/みゅ/g, "myu ");
        ship = ship.replace(/みょ/g, "myo ");
        ship = ship.replace(/りゃ/g, "rya ");
        ship = ship.replace(/りゅ/g, "ryu ");
        ship = ship.replace(/りょ/g, "ryo ");
        ship = ship.replace(/ぎゃ/g, "gya ");
        ship = ship.replace(/ぎゅ/g, "gyu ");
        ship = ship.replace(/ぎょ/g, "gyo ");
        ship = ship.replace(/びゃ/g, "bya ");
        ship = ship.replace(/びゅ/g, "byu ");
        ship = ship.replace(/びょ/g, "byo ");
        ship = ship.replace(/ぴゃ/g, "pya ");
        ship = ship.replace(/ぴゅ/g, "pyu ");
        ship = ship.replace(/ぴょ/g, "pyo ");
        ship = ship.replace(/じゃ/g, "ja ");
        ship = ship.replace(/じゅ/g, "ju ");
        ship = ship.replace(/じょ/g, "jo ");
        ship = ship.replace(/ば/g, "ba ");
        ship = ship.replace(/だ/g, "da ");
        ship = ship.replace(/が/g, "ga ");
        ship = ship.replace(/は/g, "ha ");
        ship = ship.replace(/か/g, "ka ");
        ship = ship.replace(/ま/g, "ma ");
        ship = ship.replace(/な/g, "na ");
        ship = ship.replace(/ぱ/g, "pa ");
        ship = ship.replace(/ら/g, "ra ");
        ship = ship.replace(/さ/g, "sa ");
        ship = ship.replace(/た/g, "ta ");
        ship = ship.replace(/わ/g, "wa ");
        ship = ship.replace(/や/g, "ya ");
        ship = ship.replace(/ざ/g, "za ");
        ship = ship.replace(/べ/g, "be ");
        ship = ship.replace(/で/g, "de ");
        ship = ship.replace(/げ/g, "ge ");
        ship = ship.replace(/へ/g, "he ");
        ship = ship.replace(/け/g, "ke ");
        ship = ship.replace(/め/g, "me ");
        ship = ship.replace(/ね/g, "ne ");
        ship = ship.replace(/ぺ/g, "pe ");
        ship = ship.replace(/れ/g, "re ");
        ship = ship.replace(/ゑ/g, "we ");
        ship = ship.replace(/せ/g, "se ");
        ship = ship.replace(/て/g, "te ");
        ship = ship.replace(/ぜ/g, "ze ");
        ship = ship.replace(/び/g, "bi ");
        ship = ship.replace(/ぎ/g, "gi ");
        ship = ship.replace(/ひ/g, "hi ");
        ship = ship.replace(/き/g, "ki ");
        ship = ship.replace(/し/g, "si ");
        ship = ship.replace(/ち/g, "ti ");
        ship = ship.replace(/み/g, "mi ");
        ship = ship.replace(/に/g, "ni ");
        ship = ship.replace(/ぴ/g, "pi ");
        ship = ship.replace(/り/g, "ri ");
        ship = ship.replace(/ゐ/g, "wi ");
        ship = ship.replace(/じ/g, "ji ");
        ship = ship.replace(/じ/g, "zi ");
        ship = ship.replace(/ぼ/g, "bo ");
        ship = ship.replace(/ど/g, "do ");
        ship = ship.replace(/ご/g, "go ");
        ship = ship.replace(/ほ/g, "ho ");
        ship = ship.replace(/こ/g, "ko ");
        ship = ship.replace(/も/g, "mo ");
        ship = ship.replace(/の/g, "no ");
        ship = ship.replace(/ぽ/g, "po ");
        ship = ship.replace(/ろ/g, "ro ");
        ship = ship.replace(/そ/g, "so ");
        ship = ship.replace(/と/g, "to ");
        ship = ship.replace(/を/g, "wo ");
        ship = ship.replace(/よ/g, "yo ");
        ship = ship.replace(/ぞ/g, "zo ");
        ship = ship.replace(/ぶ/g, "bu ");
        ship = ship.replace(/ぐ/g, "gu ");
        ship = ship.replace(/ふ/g, "fu ");
        ship = ship.replace(/ふ/g, "hu ");
        ship = ship.replace(/く/g, "ku ");
        ship = ship.replace(/む/g, "mu ");
        ship = ship.replace(/ぬ/g, "nu ");
        ship = ship.replace(/ぷ/g, "pu ");
        ship = ship.replace(/る/g, "ru ");
        ship = ship.replace(/す/g, "su ");
        ship = ship.replace(/つ/g, "tu ");
        ship = ship.replace(/ゆ/g, "yu ");
        ship = ship.replace(/ず/g, "zu ");

        // cas des doublons
        ship = ship.replace(/ぢ/g, "di ");
        ship = ship.replace(/づ/g, "du ");

        ship = ship.replace(/あ/g, "a ");
        ship = ship.replace(/い/g, "i ");
        ship = ship.replace(/え/g, "e ");
        ship = ship.replace(/お/g, "o ");
        ship = ship.replace(/う/g, "u ");
        ship = ship.replace(/ゔ/g, "v ");

        pronuciation.value = ship;
        if (pronuciation.value != "") {
            pronuciation.classList.remove("hidden");
        } else {
            pronuciation.classList.add("hidden");
        }
        pronuciationCopy.value = pronuciation.value;
    };
}
